- name: Bootstrap WSL
  hosts: wsl
  ### Go here to edit variables ###
  vars_files:
    - "{{ lookup('ansible.builtin.env', 'LOCALDEV_OVERRIDE_PATH', default='') }}vars/user_environment.yml"
    - "{{ lookup('ansible.builtin.env', 'LOCALDEV_OVERRIDE_PATH', default='') }}vars/network.yml"
    - "{{ lookup('ansible.builtin.env', 'LOCALDEV_OVERRIDE_PATH', default='') }}vars/prerequisite_packages.yml"
    - "{{ lookup('ansible.builtin.env', 'LOCALDEV_OVERRIDE_PATH', default='') }}vars/tool_versions.yml"

  ### Comment out roles you don't need ###
  roles:
    - {role: 'packages', tags: 'packages'}
    # - {role: 'shell', tags: 'shell'}
    # - {role: 'workspace', tags: 'workspace'}
    - {role: 'ops', tags: 'ops'}
    - {role: 'kubernetes', tags: 'kubernetes'}

  ### Change to your user! ###
  user: "{{ default_user }}"
