# code: language=ansible
---
- name: Wait until metallb-system is up
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: metallb-system
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  
- name: MetalLB Fix Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: metallb-fix-yml.j2
    dest: "{{ metallb_fix_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy MetalLB Fix
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    #namespace: kube-system
    state: present
    src: "{{ metallb_fix_yml }}"
    wait: yes
