# code: language=ansible
---
- name: Configure microk8s options
  become: true
  ansible.builtin.template:
    src: etc-microk8s-yml.j2
    dest: /etc/microk8s.yaml
    backup: true
    mode: 'u=rw,g=r,o=r'

- name: Install microk8s
  become: true
  community.general.snap:
    name: microk8s
    state: present
    classic: true
    channel: "{{ microk8s_channel }}"

- name: Start microk8s
  become: true
  ansible.builtin.command: |
    microk8s start
  changed_when: false

- name: Wait for microk8s to be ready
  become: true
  ansible.builtin.command: |
    microk8s status --wait-ready
  changed_when: false
  register: microk8s_wait_for_ready_status_out
  failed_when:
      - microk8s_wait_for_ready_status_out.rc > 0

- name: Set microk8s group members
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  with_items:
    - "{{ user }}"
  register: add_to_microk8s_group_result

- name: Include reset connection tasks
  ansible.builtin.include_tasks: reset-connection.yml
  when: add_to_microk8s_group_result.changed == true

- name: Create .kube folder for root
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/root/.kube"
    state: directory
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rwx,o='
    recurse: true

- name: Create .kube folder for user
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 'u=rwx,g=rwx,o='
    recurse: true

- name: Get MicroK8s config
  become: true
  ansible.builtin.command: /snap/bin/microk8s config
  register: microk8s_config
  changed_when: false  # Avoid unnecessary changes detection
  check_mode: no  # Ensure it runs even in check mode

- name: Ensure .kube directory exists for root
  become: true
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Ensure .kube directory exists for user
  become: true
  ansible.builtin.file:
    path: /home/{{ user }}/.kube
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0700'

- name: Update kubectl config for root if changed
  become: true
  ansible.builtin.copy:
    content: "{{ microk8s_config.stdout }}"
    dest: /root/.kube/config
    mode: '0600'
  #diff: true

- name: Update kubectl config for user if changed
  become: true
  ansible.builtin.copy:
    content: "{{ microk8s_config.stdout }}"
    dest: /home/{{ user }}/.kube/config
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0600'
  #diff: true

- name: Check if nvidia device
  ansible.builtin.stat:
    path:  /mnt/c/Windows/System32/lxss/lib/libcuda.so.1.1
  register: folder_check

- name: Set variable if folder exists
  ansible.builtin.set_fact:
    use_nvidia: "{{ folder_check.stat.exists | default(false) }}"

- name: Use nvidia runtime as default runtime
  become: true
  ansible.builtin.replace:
    path: /var/snap/microk8s/current/args/containerd-template.toml
    regexp: 'default_runtime_name = "\${RUNTIME}"'
    replace: 'default_runtime_name = "nvidia"'
  when: use_nvidia|default(false)|bool
  register: changed_default_runtime_name

- name: Rename nvidia-container-runtime to nvidia
  become: true
  ansible.builtin.replace:
    path: /var/snap/microk8s/current/args/containerd-template.toml
    regexp: 'runtimes\.nvidia-container-runtime'
    replace: 'runtimes.nvidia'
  when: changed_default_runtime_name.changed

- name: Stop microk8s
  become: true
  ansible.builtin.command: |
    microk8s stop
  changed_when: false
  register: microk8s_stop_status_out
  failed_when:
    - microk8s_stop_status_out.rc > 0
  when: changed_default_runtime_name.changed
  
- name: Wait for MicroK8s to stop
  become: true
  ansible.builtin.command: |
    microk8s status
  register: microk8s_status_stopped
  until: microk8s_status_stopped.stdout.find('microk8s is not running') != -1
  retries: 30
  delay: 10
  when: changed_default_runtime_name.changed

- name: Start microk8s
  become: true
  ansible.builtin.command: |
    microk8s start
  changed_when: false
  register: microk8s_start_status_out
  failed_when:
    - microk8s_start_status_out.rc > 0
  when: changed_default_runtime_name.changed

- name: Wait for microk8s to be ready
  become: true
  ansible.builtin.command: |
    microk8s status --wait-ready
  register: microk8s_wait_for_ready_status_out
  failed_when:
      - microk8s_wait_for_ready_status_out.rc > 0
  when: changed_default_runtime_name.changed
