# code: language=ansible
---
- name: Add an apt signing key for nvidia-docker
  become: true
  ansible.builtin.get_url:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    dest: /usr/share/keyrings/nvidia-docker.asc
    mode: 'u=rw,g=r,o=r'
    force: true
  when: use_nvidia|default(false)|bool

- name: Add an apt source for libnvidia-container
  become: true
  ansible.builtin.template:
    src: libnvidia-container-list.j2
    dest: "/etc/apt/sources.list.d/libnvidia-container.list"
    mode: 'u=rw,g=r,o=r'
  when: use_nvidia|default(false)|bool

- name: Install Nvidia Container Toolkit
  become: true
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    state: "present"
    update_cache: yes
  when: use_nvidia|default(false)|bool
  register: install_nvidia_container_toolkit_result

# - name: Restart Docker service
#   become: true
#   ansible.builtin.service:
#     name: docker
#     state: restarted
#   when: use_nvidia|default(false)|bool
#   changed_when: install_nvidia_container_toolkit_result.changed

# - name: Check NVidia can be reached from Docker
#   become: true
#   docker_container:
#     name: docker-nvidia-gpu-test
#     image: "{{ docker_nvidia_test_image }}"
#     command: nvidia-smi
#     auto_remove: true
#     detach: false
#     runtime: nvidia
#     device_requests:
#       - count: -1  # all
#         capabilities:
#         - gpu
#   when: use_nvidia|default(false)|bool
#   changed_when: install_nvidia_container_toolkit_result.changed
