# code: language=ansible
---

check_helm_deployment: true

######################################################
## Cilium
######################################################

cilium_helm_version: "v1.17.3"
cilium_helm_overrides: "{{ download_path }}/cilium-overrides.yml"
cilium_k8s_service_host: "{{ wsl_host_primary_ipv4_address }}"
cilium_crds_yml: "{{ download_path }}/cilium-crds.yml"

cilium_cluster_pool_ipv4_pod_cidr_list: ["{{ kubernetes_cluster_network_ipv4_cidr }}"]
cilium_cluster_pool_ipv4_mask_size: "22" #/16
cilium_cluster_pool_ipv6_pod_cidr_list: ["{{ kubernetes_cluster_network_ipv6_cidr }}"]
cilium_cluster_pool_ipv6_mask_size: "80" #/64
cilium_ipv4_native_routing_cidr: "{{ wsl_host_primary_ipv4_network_cidr }}"
cilium_ipv6_native_routing_cidr: "{{ wsl_host_primary_ipv6_network_cidr }}"
cilium_ipv4_enabled: "{{ 'true' if cilium_ipv4_native_routing_cidr | length > 0 else 'false' }}"
cilium_ipv6_enabled: "{{ 'true' if cilium_ipv6_native_routing_cidr | length > 0 else 'false' }}"

cilium_load_balancer_pool_ipv4: "{{ kubernetes_external_network_ipv4_cidr }}"
cilium_load_balancer_pool_ipv6: "{{ kubernetes_external_network_ipv6_cidr }}"

######################################################
## Host path provider
######################################################

host_path_provider_yml: "{{ download_path }}/hostpath-provisioner.yml"
host_path_provider_pv_dir: "{{ '/var/snap/microk8s/common/default-storage' if k8s_distribution == 'microk8s' else '/opt/local-path-provisioner' }}"

######################################################
## CoreDns
######################################################

coredns_helm_version: "1.42.1"
coredns_helm_overrides: "{{ download_path }}/coredns-overrides.yml"

coredns_cluster_name: "{{ cluster_name }}"
coredns_tld: "{{ tld }}"
coredns_primary_dns_ipv4: "{{ kubernetes_cluster_service_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('4') | ansible.utils.ipaddr('address') }}"
coredns_primary_dns_ipv6: "{{ kubernetes_cluster_service_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('4') | ansible.utils.ipaddr('address') }}"
coredns_external_domain: "{{ coredns_cluster_name }}.{{ coredns_tld }}"
coredns_internal_domain: "svc.cluster.local"
coredns_upstream_dnsserver: "{{ wsl_host_all_dns_servers | map('regex_replace', '^([0-9a-fA-F:]+)$', '[\\1]') | map('regex_replace', '^(.+)$', 'dns://\\1:53') | join(' ') }}"

######################################################
## External CoreDns
######################################################

external_coredns_helm_version: "1.42.1"
external_coredns_helm_overrides: "{{ download_path }}/external-coredns-overrides.yml"

external_coredns_cluster_name: "{{ cluster_name }}"
external_coredns_tld: "{{ tld }}"
external_coredns_primary_dns_ipv4: "{{ kubernetes_cluster_service_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('14') | ansible.utils.ipaddr('address') }}"
external_coredns_primary_dns_ipv6: "{{ kubernetes_cluster_service_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('14') | ansible.utils.ipaddr('address') }}"
external_coredns_domain: "{{ external_coredns_cluster_name }}.{{ external_coredns_tld }}"
external_coredns_etcd_address: "https://etcd.etcd.svc.cluster.local:{{ etcd_service_port_client }}"
external_coredns_etcd_cert_manager_crds_yml: "{{ download_path }}/external-coredns-etcd-cert-manager-crds.yml"

######################################################
## Exernal-DNS
######################################################

external_dns_helm_version: "1.16.1"
external_dns_helm_overrides: "{{ download_path }}/external-dns-overrides.yml"

external_dns_etcd_cert_manager_crds_yml: "{{ download_path }}/external-dns-etcd-cert-manager-crds.yml"
external_dns_etcd_address: "https://etcd.etcd.svc.cluster.local:{{ etcd_service_port_client }}"

######################################################
## etcd
######################################################

etcd_helm_version: "11.3.4"
etcd_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('6') | ansible.utils.ipaddr('address') }}"
etcd_helm_overrides: "{{ download_path }}/etcd-overrides.yml"
etcd_cert_manager_crds_yml: "{{ download_path }}/etcd-cert-manager-crds.yml"
etcd_volume_size: 1Gi
etcd_service_port_client: 2379

######################################################
## K8S Gateway
######################################################

k8s_gateway_helm_version: "2.4.0"
k8s_gateway_primary_helm_overrides: "{{ download_path }}/external-dns-primary-overrides.yml"
k8s_gateway_secondary_helm_overrides: "{{ download_path }}/external-dns-secondary-overrides.yml"

k8s_gateway_cluster_name: "{{ cluster_name }}"
k8s_gateway_tld: "{{ tld }}"
k8s_gateway_domain: "{{ k8s_gateway_cluster_name }}.{{ k8s_gateway_tld }}"

k8s_gateway_external_primary_dns_ipv4: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('4') | ansible.utils.ipaddr('address') }}"
k8s_gateway_external_primary_dns_ipv6: "{{ kubernetes_external_network_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('4') | ansible.utils.ipaddr('address') }}"

k8s_gateway_external_secondary_dns_ipv4: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('5') | ansible.utils.ipaddr('address') }}"
k8s_gateway_external_secondary_dns_ipv6: "{{ kubernetes_external_network_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('5') | ansible.utils.ipaddr('address') }}"

######################################################
## NFS CSI
######################################################

nfs_csi_helm_version: "v4.11.0"
nfs_csi_helm_overrides: "{{ download_path }}/nfs-csi-overrides.yml"
nfs_csi_kublet: "{{ '/var/snap/microk8s/common/var/lib/kubelet' if k8s_distribution == 'microk8s' else '/var/lib/kubelet' }}"

######################################################
## SMB CSI
######################################################

smb_csi_helm_value: "v1.17.0"
smb_csi_helm_overrides: "{{ download_path }}/smb-csi-overrides.yml"
smb_csi_kublet: "{{ '/var/snap/microk8s/common/var/lib/kubelet' if k8s_distribution == 'microk8s' else '/var/lib/kubelet' }}"

######################################################
## Traefik
######################################################

traefik_helm_version: "35.2.0"
traefik_helm_overrides: "{{ download_path }}/traefik-overrides.yml"
traefik_dashboard_yml: "{{ download_path }}/traefik-dashboard.yml"

traefik_cluster_name: "{{ cluster_name }}"
traefik_tld: "{{ tld }}"

traefik_ingress_ipv4: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('3') | ansible.utils.ipaddr('address') }}"
traefik_ingress_ipv6: "{{ kubernetes_external_network_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('3') | ansible.utils.ipaddr('address') }}"
traefik_trusted_ips: >-
  {{ ["127.0.0.1/32", "::1/128"] + (wsl_host_primary_all_cidr | default([]) | list) }}

######################################################
## ApiSix
######################################################

apisix_helm_version: "2.10.0"
apisix_helm_overrides: "{{ download_path }}/apisix-overrides.yml"
apisix_cluster_name: "{{ cluster_name }}"
apisix_tld: "{{ tld }}"

apisix_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('9') | ansible.utils.ipaddr('address') }}"
apisix_ingress_ipv4: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('10') | ansible.utils.ipaddr('address') }}"
apisix_ingress_ipv6: "{{ kubernetes_external_network_ipv6_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('10') | ansible.utils.ipaddr('address') }}"

######################################################
## Cert Manager
######################################################

cert_manager_helm_version: "v1.17.2"
cert_manager_helm_overrides: "{{ download_path }}/cert-manager-overrides.yml"
cert_manager_crds_yml: "{{ download_path }}/cert-manager-crds.yml"

######################################################
## Trust Manager
######################################################

trust_manager_helm_version: "v0.17.1"
trust_manager_helm_overrides: "{{ download_path }}/trust-manager-overrides.yml"
trust_manager_crds_yml: "{{ download_path }}/trust-manager-crds.yml"

######################################################
## Metrics Server
######################################################

metrics_server_helm_version: "v3.12.2"
metrics_server_helm_overrides: "{{ download_path }}/metrics-server-overrides.yml"

######################################################
## Kube Prometheus Stack
######################################################

kube_prometheus_stack_helm_version: "72.2.0"
kube_prometheus_stack_helm_overrides: "{{ download_path }}/kube-prometheus-stack-overrides.yml"
kube_prometheus_stack_cluster_name: "{{ cluster_name }}"
kube_prometheus_stack_tld: "{{ tld }}"

######################################################
## External Secrets
######################################################

external_secrets_helm_version: "0.16.2"
external_secrets_helm_overrides: "{{ download_path }}/external-secrets-overrides.yml"
external_secrets_crds_yml: "{{ download_path }}/external-secrets-crds.yml"

######################################################
## WhoAmI
######################################################

whoami_helm_version: "5.1.1"
whoami_helm_overrides: "{{ download_path }}/whoami-overrides.yml"
whoami_cluster_name: "{{ cluster_name }}"
whoami_tld: "{{ tld }}"
whoami_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('13') | ansible.utils.ipaddr('address') }}"

######################################################
## Postgres Operator
######################################################

postgres_operator_helm_version: "1.14.0"
postgres_operator_helm_overrides: "{{ download_path }}/postgres-operator-overrides.yml"

######################################################
## Postgres Operator UI
######################################################

postgres_operator_ui_helm_version: "1.14.0"
postgres_operator_ui_helm_overrides: "{{ download_path }}/postgres-operator-ui-overrides.yml"
postgres_operator_ui_cluster_name: "{{ cluster_name }}"
postgres_operator_ui_tld: "{{ tld }}"
postgres_operator_ui_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('7') | ansible.utils.ipaddr('address') }}"

######################################################
## Postgres Cluster
######################################################

postgres_cluster_yml: "{{ download_path }}/postgres-cluster.yml"

postgres_cluster_name: postgres-cluster
postgres_cluster_volume_size: 1Gi
postgres_cluster_instances: 1

postgres_cluster_flowise_database_name: flowise
postgres_cluster_flowise_database_username: flowise.flowise
postgres_cluster_n8n_database_name: n8n
postgres_cluster_n8n_database_username: n8n.n8n
postgres_cluster_temporal_database_name: temporal
postgres_cluster_temporal_database_username: temporal.temporal
postgres_cluster_temporal_visibility_database_name: temporal-visibility
postgres_cluster_temporal_visibility_database_username: temporal-visibility.temporal-visibility

postgres_cluster_users: |
    {{ postgres_cluster_flowise_database_username }}:
    - superuser
    - createdb
    {{ postgres_cluster_n8n_database_username }}:
    - superuser
    - createdb
    {{ postgres_cluster_temporal_database_username }}:
    - superuser
    - createdb
    {{ postgres_cluster_temporal_visibility_database_username }}:
    - superuser
    - createdb

postgres_cluster_databases: |
    {{ postgres_cluster_flowise_database_name }}: {{ postgres_cluster_flowise_database_username }}
    {{ postgres_cluster_n8n_database_name }}: {{ postgres_cluster_n8n_database_username }}
    {{ postgres_cluster_temporal_database_name }}: {{ postgres_cluster_temporal_database_username }}
    {{ postgres_cluster_temporal_visibility_database_name }}: {{ postgres_cluster_temporal_visibility_database_username }}

######################################################
## Redis Operator
######################################################

redis_operator_prerequisites_yml: "{{ download_path }}/redis-operator-prerequisites.yml"
redis_operator_helm_version: "0.20.1"
redis_operator_helm_image_tag: "v0.20.1"
redis_operator_helm_overrides: "{{ download_path }}/redis-operator-overrides.yml"

######################################################
## Redis
######################################################

redis_helm_version: "0.16.5"
redis_helm_image_tag: "v7.0.15"
redis_prerequisites_yml: "{{ download_path }}/redis-prerequisites.yml"
redis_helm_overrides: "{{ download_path }}/redis-overrides.yml"
redis_password: "redis_P@ssw0rd"
redis_name: redis
redis_volume_size: 1Gi

######################################################
## RabbitMQ Cluster Operator
######################################################

rabbitmq_cluster_operator_helm_version: "4.4.9"
rabbitmq_cluster_operator_helm_overrides: "{{ download_path }}/rabbitmq-cluster-operator-overrides.yml"

######################################################
## RabbitMQ Cluster
######################################################

rabbitmq_cluster_yml: "{{ download_path }}/rabbitmq-cluster.yml"

rabbitmq_cluster_name: rabbitmq-cluster
rabbitmq_cluster_volume_size: 1Gi
rabbitmq_cluster_instances: 1

######################################################
## OpenSearch Operator
######################################################

opensearch_operator_helm_version: "2.7.0"
opensearch_operator_helm_overrides: "{{ download_path }}/opensearch-operator-overrides.yml"
opensearch_operator_ui_cluster_name: "{{ cluster_name }}"
opensearch_operator_ui_tld: "{{ tld }}"
opensearch_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('8') | ansible.utils.ipaddr('address') }}"

######################################################
## OpenSearch Cluster
######################################################
opensearch_cluster_helm_version: "3.0.0"
opensearch_cluster_helm_overrides: "{{ download_path }}/opensearch-cluster.yml"

opensearch_cluster_name: opensearch-cluster
opensearch_cluster_volume_size: 1Gi
opensearch_cluster_instances: 1

######################################################
## Ollama
######################################################

ollama_use_external_service: true
ollama_external_yml: "{{ download_path }}/ollama-external.yml"
ollama_helm_version: "1.16.0"
ollama_helm_image_tag: "0.6.8"
ollama_helm_overrides: "{{ download_path }}/ollama-overrides.yml"
ollama_cluster_name: "{{ cluster_name }}"
ollama_tld: "{{ tld }}"
ollama_gpu_enabled: "false"
ollama_number_of_gpus: "2"
ollama_default_model: "deepseek-r1:70b"

######################################################
## Open WebUI
######################################################

open_webui_helm_version: "6.11.0"
open_webui_helm_image_tag: "v0.6.7" #https://github.com/orgs/open-webui/packages/container/open-webui/versions
open_webui_helm_overrides: "{{ download_path }}/open-webui-overrides.yml"
open_webui_cluster_name: "{{ cluster_name }}"
open_webui_tld: "{{ tld }}"

######################################################
## Qdrant
######################################################

qdrant_helm_version: "1.14.0"
qdrant_helm_overrides: "{{ download_path }}/qdrant-overrides.yml"
qdrant_cluster_name: "{{ cluster_name }}"
qdrant_tld: "{{ tld }}"

######################################################
## Flowise
######################################################

flowise_helm_version: "3.11.4"
flowise_helm_image_tag: "2.2.8"
flowise_helm_overrides: "{{ download_path }}/flowise-overrides.yml"
flowise_cluster_name: "{{ cluster_name }}"
flowise_tld: "{{ tld }}"
flowise_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('11') | ansible.utils.ipaddr('address') }}"

######################################################
## N8N
######################################################

n8n_helm_version: "1.0.6"
n8n_helm_image_tag: "1.92.2"
n8n_helm_overrides: "{{ download_path }}/n8n-overrides.yml"
n8n_cluster_name: "{{ cluster_name }}"
n8n_tld: "{{ tld }}"
n8n_load_balancer_ip: "{{ kubernetes_external_network_ipv4_cidr | ansible.utils.ipaddr('network') | ansible.utils.ipmath('12') | ansible.utils.ipaddr('address') }}"
n8n_volume_size: 1Gi
n8n_instances: 1

######################################################
## Node Red
######################################################
node_red_helm_version: "0.34.0"
node_red_helm_image_tag: "latest-22"
node_red_helm_overrides: "{{ download_path }}/node-red-overrides.yml"
node_red_cluster_name: "{{ cluster_name }}"
node_red_tld: "{{ tld }}"
node_red_volume_size: 1Gi

######################################################
## Temporal
######################################################

temporal_helm_version: "0.62.0"
temporal_helm_overrides: "{{ download_path }}/temporal-overrides.yml"
temporal_cluster_name: "{{ cluster_name }}"
temporal_tld: "{{ tld }}"
temporal_volume_size: 1Gi
