# code: language=ansible
---
- name: Cilium Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cilium-overrides-yml.j2
    dest: "{{ cilium_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: cilium_helm_overrides_result

- name: Add Cilium chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: Deploy Cilium helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: cilium
    release_namespace: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ cilium_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ cilium_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (cilium_helm_overrides_result.changed | default(true))

- name: Wait for all required Cilium CRDs to be established
  become: true
  become_user: '{{ user }}'
  retries: 15
  delay: 10
  until: crds_info.resources | length >= required_crd_count and
         (crds_info.resources | selectattr('status.conditions', 'defined') | selectattr('status.conditions', '!=', []) | list | length) >= required_crd_count
  vars:
    required_crd_count: 10  # Adjust based on expected number of CRDs
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
  register: crds_info

- name: cilium crds Yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cilium-crds-yml.j2
    dest: "{{ cilium_crds_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy cilium crds
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: cilium
    state: present
    src: "{{ cilium_crds_yml }}"
    wait: yes