# code: language=ansible
---
- name: CoreDNS Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: coredns-overrides-yml.j2
    dest: "{{ coredns_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: coredns_helm_overrides_result

- name: Add CoreDNS chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: coredns
    repo_url: "https://coredns.github.io/helm"

- name: Deploy CoreDNS helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: coredns
    release_namespace: coredns
    chart_ref: coredns/coredns
    chart_version: "{{ coredns_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ coredns_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ coredns_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (coredns_helm_overrides_result.changed | default(true))