# code: language=ansible
---
- name: Hostpath Provisioner Yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: hostpath-provisioner-yml.j2
    dest: "{{ host_path_provider_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy hostpath provisioner
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    #namespace: kube-system
    state: present
    src: "{{ host_path_provider_yml }}"
    wait: yes
