# code: language=ansible
---
- name: Get host information
  ansible.builtin.include_tasks: host.yml
- name: Cilium
  ansible.builtin.include_tasks: cilium.yml
- name: Hostpath Provisioner
  ansible.builtin.include_tasks: hostpath-provisioner.yml
- name: Core DNS
  ansible.builtin.include_tasks: coredns.yml
# - name: K8S Gateway
#   ansible.builtin.include_tasks: k8s-gateway.yml
- name: NFS CSI
  ansible.builtin.include_tasks: nfs-csi.yml
- name: SMB CSI
  ansible.builtin.include_tasks: smb-csi.yml
- name: Cert Manager
  ansible.builtin.include_tasks: cert-manager.yml
- name: Trust Manager
  ansible.builtin.include_tasks: trust-manager.yml
- name: External-Secrets
  ansible.builtin.include_tasks: external-secrets.yml
- name: ETCD
  ansible.builtin.include_tasks: etcd.yml
- name: External Core DNS
  ansible.builtin.include_tasks: external-coredns.yml
- name: External DNS
  ansible.builtin.include_tasks: external-dns.yml
- name: Traefik
  ansible.builtin.include_tasks: traefik.yml
# - name: ApiSix
#   ansible.builtin.include_tasks: apisix.yml
# - name: Metrics Server
#   ansible.builtin.include_tasks: metrics-server.yml
- name: Kube Prometheus Stack
  ansible.builtin.include_tasks: kube-prometheus-stack.yml
- name: WhoAmI
  ansible.builtin.include_tasks: whoami.yml
- name: Postgres Operator
  ansible.builtin.include_tasks: postgres-operator.yml
- name: Postgres Operator UI
  ansible.builtin.include_tasks: postgres-operator-ui.yml
- name: Postgres Cluster
  ansible.builtin.include_tasks: postgres-cluster.yml
- name: Redis Operator
  ansible.builtin.include_tasks: redis-operator.yml
- name: Redis
  ansible.builtin.include_tasks: redis.yml
- name: RabbitMQ Cluster Operator
  ansible.builtin.include_tasks: rabbitmq-cluster-operator.yml
- name: RabbitMQ Cluster
  ansible.builtin.include_tasks: rabbitmq-cluster.yml
# - name: OpenSearch Operator
#   ansible.builtin.include_tasks: opensearch-operator.yml
# - name: OpenSearch Cluster
#   ansible.builtin.include_tasks: opensearch-cluster.yml
- name: Ollama
  ansible.builtin.include_tasks: ollama.yml
- name: Open WebUI
  ansible.builtin.include_tasks: open-webui.yml
- name: Qdrant
  ansible.builtin.include_tasks: qdrant.yml
- name: Flowise
  ansible.builtin.include_tasks: flowise.yml
# - name: N8N
#   ansible.builtin.include_tasks: n8n.yml
# - name: Node Red
#   ansible.builtin.include_tasks: node-red.yml
# - name: Temporal Red
#   ansible.builtin.include_tasks: temporal.yml

- name: Manual host setup instructions
  ansible.builtin.include_tasks: manual-host-setup.yml
