# code: language=ansible
---

- name: Ollama proxy service yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: ollama-external-yml.j2
    dest: "{{ ollama_external_yml }}"
    mode: 'u=rw,g=r,o=r'
  when: ollama_use_external_service

- name: Deploy external Ollama proxy services
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    state: present
    src: "{{ ollama_external_yml }}"
    wait: yes
  when: ollama_use_external_service

- name: Ollama Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: ollama-overrides-yml.j2
    dest: "{{ ollama_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  when: not ollama_use_external_service
  register: ollama_helm_overrides_result

- name: Add Ollama chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: ollama
    repo_url: "https://otwld.github.io/ollama-helm/"
  when: not ollama_use_external_service

- name: Deploy Ollama helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: ollama
    release_namespace: ollama
    chart_ref: ollama/ollama
    chart_version: "{{ ollama_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ ollama_use_external_service.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ ollama_helm_overrides }}"
  when: not ollama_use_external_service and ((check_helm_deployment | default(true)) or (ollama_use_external_service.changed | default(true)))
