# code: language=ansible
---
#https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/Chart.yaml
- name: Postgres Operator UI Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: postgres-operator-ui-overrides-yml.j2
    dest: "{{ postgres_operator_ui_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: postgres_operator_ui_helm_overrides_result

- name: Add Postgres Operator UI chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: postgres-operator-ui
    repo_url: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui"

- name: Deploy Postgres Operator UI helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: postgres-operator-ui
    release_namespace: postgres-operator-ui
    chart_ref: postgres-operator-ui/postgres-operator-ui
    chart_version: "{{ postgres_operator_ui_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ postgres_operator_ui_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ postgres_operator_ui_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (postgres_operator_ui_helm_overrides_result.changed | default(true))
