# code: language=ansible
---
#https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq-cluster-operator/Chart.yaml
- name: RabbitMQ Cluster Operator Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: rabbitmq-cluster-operator-overrides-yml.j2
    dest: "{{ rabbitmq_cluster_operator_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: rabbitmq_cluster_operator_helm_overrides_result

- name: Add RabbitMQ Cluster Operator chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: rabbitmq-cluster-operator
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy RabbitMQ Cluster Operator helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: rabbitmq-cluster-operator
    release_namespace: rabbitmq-cluster-operator
    chart_ref: rabbitmq-cluster-operator/rabbitmq-cluster-operator
    chart_version: "{{ rabbitmq_cluster_operator_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ rabbitmq_cluster_operator_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ rabbitmq_cluster_operator_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (rabbitmq_cluster_operator_helm_overrides_result.changed | default(true))
