# code: language=ansible
---
#https://github.com/OT-CONTAINER-KIT/redis/blob/master/charts/redis/Chart.yaml
- name: Redis Prerequisites
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: redis-prerequisites-yml.j2
    dest: "{{ redis_prerequisites_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Create Redis namespace
  kubernetes.core.k8s:
    name: redis
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Redis Prerequisites
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: redis
    state: present
    src: "{{ redis_prerequisites_yml }}"
    wait: yes

- name: Redis Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: redis-overrides-yml.j2
    dest: "{{ redis_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: redis_helm_overrides_result

- name: Add Redis chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: redis
    repo_url: "https://ot-container-kit.github.io/helm-charts"

- name: Deploy Redis helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: redis
    release_namespace: redis
    chart_ref: redis/redis
    chart_version: "{{ redis_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ redis_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ redis_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (redis_helm_overrides_result.changed | default(true))
