# code: language=ansible
---
#https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/charts/redis-operator/Chart.yaml
- name: Redis Operator Prerequisites
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: redis-operator-prerequisites-yml.j2
    dest: "{{ redis_operator_prerequisites_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Create Redis Operator namespace
  kubernetes.core.k8s:
    name: redis-operator
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy Redis Operator Prerequisites
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: redis-operator
    state: present
    src: "{{ redis_operator_prerequisites_yml }}"
    wait: yes

- name: Redis Operator Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: redis-operator-overrides-yml.j2
    dest: "{{ redis_operator_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: redis_operator_helm_overrides_result

- name: Add Redis Operator chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: redis-operator
    repo_url: "https://ot-container-kit.github.io/helm-charts"

- name: Deploy Redis Operator helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: redis-operator
    release_namespace: redis-operator
    chart_ref: redis-operator/redis-operator
    chart_version: "{{ redis_operator_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ redis_operator_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ redis_operator_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (redis_operator_helm_overrides_result.changed | default(true))
