# code: language=ansible
---
- name: Temporal Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: temporal-overrides-yml.j2
    dest: "{{ temporal_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: temporal_helm_overrides_result

- name: Add Temporal chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: temporal
    repo_url: "https://go.temporal.io/helm-charts"

- name: Deploy Temporal helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: temporal
    release_namespace: temporal
    chart_ref: temporal/temporal
    chart_version: "{{ temporal_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ temporal_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ temporal_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (temporal_helm_overrides_result.changed | default(true))
