# code: language=ansible
---
- name: Traefik Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: traefik-overrides-yml.j2
    dest: "{{ traefik_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: traefik_helm_overrides_result

- name: Traefik Dashboard Yml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: traefik-dashboard-yml.j2
    dest: "{{ traefik_dashboard_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Add Traefik chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "https://helm.traefik.io/traefik"

- name: Deploy Traefik helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: traefik
    release_namespace: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_helm_version }}"
    create_namespace: true
    update_repo_cache: "{{ traefik_helm_overrides_result.changed | default(true) }}"
    wait: true
    values_files:
      - "{{ traefik_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (traefik_helm_overrides_result.changed | default(true))

- name: Deploy Traefik Dashboard
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: traefik
    state: present
    src: "{{ traefik_dashboard_yml }}"
    wait: yes
