# code: language=ansible
---
- name: Install zsh and friends
  become: True
  become_user: root
  ansible.builtin.package: name={{ item }}
  with_items:
    - git-core
    - powerline
    - zsh

- name: Change user shell to zsh
  become: true
  become_user: root
  ansible.builtin.command: chsh -s /bin/zsh {{ user }}

- name: Check for oh-my-zsh
  ansible.builtin.stat: path=/$HOME/.oh-my-zsh
  register: ohmyzsh

- name: Install oh-my-zsh
  ansible.builtin.shell: bash -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists

- name: Check for dircolors
  ansible.builtin.stat: path=/$HOME/.dircolors
  register: dircolors

- name: Install dircolors
  ansible.builtin.command: curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output /$HOME/.dircolors
  when: not dircolors.stat.exists

- name: Check for powerlevel10k
  ansible.builtin.stat: path=/$HOME/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k

- name: Clone powerlevel10k
  ansible.builtin.command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ lookup("env", "HOME") }}/.oh-my-zsh/custom/themes/powerlevel10k
  when: not powerlevel10k.stat.exists
