# code: language=ansible
---
default_user: "{{ lookup('ansible.builtin.env', 'USER', default='taliesins') }}"
user: "{{ (ansible_env.SUDO_USER is defined and ansible_env.SUDO_USER) or ansible_user_id }}"
repo_directory: workspace
repos: []
  # - git@github.com:jasonwc/noobernetes.io.git
  # - git@github.com:jasonwc/jasoncarter.io.git
  # - git@github.com:jasonwc/carter.haus.git
dotfiles_repo: taliesins/dotfiles
dotfiles_branch: master
dotfiles_command: sh install.sh
