# code: language=ansible
---
- name: Configure microk8s options
  become: true
  ansible.builtin.template:
    src: etc-microk8s-yml.j2
    dest: /etc/microk8s.yaml
    backup: true
    mode: 'u=rw,g=r,o=r'

- name: Install microk8s
  become: true
  community.general.snap:
    name: microk8s
    state: present
    classic: true
    channel: "{{ microk8s_channel }}"

- name: Wait for microk8s to be ready
  become: true
  ansible.builtin.command: |
    microk8s status --wait-ready
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - mk8sstatusout.rc > 0

- name: Set microk8s group members
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: microk8s
    append: true
  with_items:
    - "{{ user }}"
  register: add_to_microk8s_group_result

- name: Include reset connection tasks
  ansible.builtin.include_tasks: reset-connection.yml
  when: add_to_microk8s_group_result.changed == true

- name: Create .kube folder for root
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/root/.kube"
    state: directory
    owner: 'root'
    group: 'root'
    mode: 'u=rwx,g=rwx,o='
    recurse: true

- name: Create .kube folder for user
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 'u=rwx,g=rwx,o='
    recurse: true

- name: Create kubectl config for root
  become: true
  ansible.builtin.shell: |
    /snap/bin/microk8s config > /root/.kube/config
  args:
    executable: /bin/bash
    creates: /root/.kube/config

- name: Create kubectl config for user
  become: true
  ansible.builtin.shell: |
    /snap/bin/microk8s config > /home/{{ user }}/.kube/config
    chown {{ user }}:{{ user }} /home/{{ user }}/.kube/config
  args:
    executable: /bin/bash
    creates: /home/{{ user }}/.kube/config

- name: Set file permissions on ~/.kube/config for root
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/root/.kube/config"
    state: file
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=,o='

- name: Set file permissions on ~/.kube/config for user
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/home/{{ user }}/.kube/config"
    state: file
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 'u=rw,g=,o='
