# code: language=ansible
---
- name: Update package list
  become: true
  ansible.builtin.package:
    update_cache: yes

- name: Upgrade all packages
  become: true
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ prerequisite_packages }}"
