# code: language=ansible
---
- name: Install workspace directory
  ansible.builtin.file:
    path: '{{ lookup("env", "HOME") }}/{{ repo_directory }}'
    state: directory
    mode: 'u=rwx,g=rwx,o='

- name: Install workspace repos
  ansible.builtin.shell: cd {{ lookup("env", "HOME") }}/{{ repo_directory}} && (test -d `basename {{ item }} .git` || git clone {{ item }})
  with_items: "{{ repos }}"
